server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: http://localhost:10080/atzu68/greeting-config
          search-paths: src/main/resources

  kafka:
    bootstrap-servers:
      - localhost:9092